//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraping.Models.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itens
    {
        public System.Guid Id { get; set; }
        public string Lote { get; set; }
        public string Descricao { get; set; }
        public string UrlFoto { get; set; }
        public Nullable<decimal> LanceInicial { get; set; }
        public Nullable<decimal> MaiorLance { get; set; }
        public Nullable<int> QuantidadeLances { get; set; }
    }
}
